### ISSUE TITLE
Fixing `BLC.plist`

### ISSUE THREAD

**Issue by 5T33Z0** [jief666/BootloaderChooser#10]
If you try to open the `BLC.plist` in ProperTree or any other plist editor to edit or view it, there will be an error:

![01](https://github.com/jief666/BootloaderChooser/assets/76865553/43b4db74-8260-4016-949c-9dd3544d4b49)

This can be fixex by adding `</plist>` to the end of the file in TextEdit:

![03](https://github.com/jief666/BootloaderChooser/assets/76865553/3dcba907-7015-449e-8c54-f2b7af490080)

After that the file can be opened and edited:

![04](https://github.com/jief666/BootloaderChooser/assets/76865553/dda1d33d-9a4a-459b-851d-893f411d3d7e)

**Comment by jief666** [comment]
Thanks for reporting. Fixed in 1.4.
