### ISSUE TITLE
Unable to boot or even see menu

### ISSUE THREAD

**Issue by nikhilraj9999** [jief666/BootloaderChooser#2]
Please help me out with this i don't get it . I copied bootx64.efi to efi/boot folder for clover also tried with oc 0.6.1 but when i boot with legacy usb i get error boot0 error
When i boot with uefi usb i get black screen nothing else also num key hang on keyboard can't even ctlr alt del to restart . Nit see the menu 1ce even. Also tried with oc 0.7.9 still nothing i have a working oc for my hackintosh 0.7.9 . But i want this so i don't. Have to edit config.plist always to change smbios for diff macos . Please help asap

**Comment by jief666** [comment]
Sorry.
But this seems not a BootLoaderChooser issue.
Do not hijack a closed issue, please.
Maybe try in Clover general forum.
Thanks.
