### ISSUE TITLE
What is key pressed to back choose menu?

### ISSUE THREAD

**Issue by oldman20** [jief666/BootloaderChooser#4]
When you need the menu back, just boot your computer with a key pressed
I dont know what's mean of this? please explain, thank!

**Comment by jief666** [comment]
Just hold down a key on the keyboard while booting until you got the BootloaderChooser menu.

**Comment by jief666** [comment]
Any key.

**Comment by oldman20** [comment]
This is BLC.plist, i set timeout 1s
`<dict>
    <key>Timeout</key>
    <integer>1</integer>
    <key>DefaultVolume</key>
    <string>PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi</string>
    <key>debug</key>
    <string>true</string>
</dict>`

And here BLC.log
`0:100  0:100  MemLog inited, TSC freq: 2194917915
0:100  0:000  CPU was calibrated with ACPI PM Timer
0:100  0:000  BootloaderChooserX64 : Image base = 0x8D322000
0:100  0:000  Now is 16.08.2022,  08:19:16 (GMT)
0:100  0:000  Starting unknown on American Megatrends EFI
0:260  0:160  SelfDirPath = \EFI\BOOT
0:261  0:000  \EFI\BOOT\BLC.plist loaded: Success
0:261  0:000  === [ InitScreen ] ==============================
0:261  0:000  Console modes reported: 4, available modes:
0:261  0:000   - [01]: 80x25
0:261  0:000   - [03]: 100x31
0:261  0:000   - [04]: 170x40 (current mode)
0:261  0:000    Selected mode (4) is already set
0:261  0:000  === [ ScanVolumes ] =============================
0:261  0:000  === [ ScanLoaders ] =============================
0:400  0:138  UI ready
10:375  9:975  === [ StartLoader ] =============================
10:380  0:005  Start image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi
10:412  0:031  Boot image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi, status=Success
10:413  0:001  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
0:100  0:100  MemLog inited, TSC freq: 2194917915
0:100  0:000  CPU was calibrated with ACPI PM Timer
0:100  0:000  BootloaderChooserX64 : Image base = 0x8D322000
0:100  0:000  Now is 16.08.2022,  08:21:36 (GMT)
0:100  0:000  Starting unknown on American Megatrends EFI
0:471  0:371  SelfDirPath = \EFI\BOOT
0:472  0:000  \EFI\BOOT\BLC.plist loaded: Success
0:472  0:000  === [ InitScreen ] ==============================
0:516  0:044  Console modes reported: 4, available modes:
0:518  0:001   - [01]: 80x25
0:519  0:001   - [03]: 100x31
0:520  0:001   - [04]: 170x40 (current mode)
0:522  0:001    Selected mode (4) is already set
0:523  0:001  === [ ScanVolumes ] =============================
0:524  0:001  === [ ScanLoaders ] =============================
0:702  0:177  UI ready
2:752  2:049  === [ StartLoader ] =============================
2:755  0:003  Start image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi
2:785  0:029  Boot image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi, status=Success
2:786  0:001  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
0:100  0:100  MemLog inited, TSC freq: 2194917724
0:100  0:000  CPU was calibrated with ACPI PM Timer
0:100  0:000  BootloaderChooserX64 : Image base = 0x8D322000
0:100  0:000  Now is 16.08.2022,  08:29:38 (GMT)
0:100  0:000  Starting unknown on American Megatrends EFI
0:533  0:432  SelfDirPath = \EFI\BOOT
0:533  0:000  \EFI\BOOT\BLC.plist loaded: Success
0:533  0:000  === [ InitScreen ] ==============================
0:578  0:044  Console modes reported: 4, available modes:
0:579  0:001   - [01]: 80x25
0:580  0:001   - [03]: 100x31
0:582  0:001   - [04]: 170x40 (current mode)
0:583  0:001    Selected mode (4) is already set
0:584  0:001  === [ ScanVolumes ] =============================
0:586  0:001  === [ ScanLoaders ] =============================
1:260  0:674  UI ready
5:596  4:336  === [ StartLoader ] =============================
5:599  0:002  Start image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi
5:629  0:029  Boot image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi, status=Success
5:630  0:001  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
0:100  0:100  MemLog inited, TSC freq: 2194918185
0:100  0:000  CPU was calibrated with ACPI PM Timer
0:100  0:000  BootloaderChooserX64 : Image base = 0x8D322000
0:100  0:000  Now is 16.08.2022,  08:36:06 (GMT)
0:100  0:000  Starting unknown on American Megatrends EFI
0:469  0:369  SelfDirPath = \EFI\BOOT
0:469  0:000  \EFI\BOOT\BLC.plist loaded: Success
0:469  0:000  === [ InitScreen ] ==============================
0:517  0:047  Console modes reported: 4, available modes:
0:518  0:001   - [01]: 80x25
0:519  0:001   - [03]: 100x31
0:521  0:001   - [04]: 170x40 (current mode)
0:522  0:001    Selected mode (4) is already set
0:523  0:001  === [ ScanVolumes ] =============================
0:525  0:001  === [ ScanLoaders ] =============================
0:696  0:171  UI ready
7:435  6:739  === [ StartLoader ] =============================
7:436  0:001  Start image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi
7:472  0:035  Boot image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi, status=Success
7:473  0:001  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
0:100  0:100  MemLog inited, TSC freq: 2194918394
0:100  0:000  CPU was calibrated with ACPI PM Timer
0:100  0:000  BootloaderChooserX64 : Image base = 0x8D322000
0:100  0:000  Now is 16.08.2022,  08:41:49 (GMT)
0:100  0:000  Starting unknown on American Megatrends EFI
0:471  0:371  SelfDirPath = \EFI\BOOT
0:471  0:000  \EFI\BOOT\BLC.plist loaded: Success
0:471  0:000  === [ InitScreen ] ==============================
0:516  0:045  Console modes reported: 4, available modes:
0:518  0:001   - [01]: 80x25
0:519  0:001   - [03]: 100x31
0:520  0:001   - [04]: 170x40 (current mode)
0:522  0:001    Selected mode (4) is already set
0:523  0:001  === [ ScanVolumes ] =============================
0:524  0:001  === [ ScanLoaders ] =============================
0:697  0:172  UI ready
1:906  1:208  === [ StartLoader ] =============================
1:907  0:001  Start image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi
1:937  0:029  Boot image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi, status=Success
1:938  0:001  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
0:100  0:100  MemLog inited, TSC freq: 2194928044
0:100  0:000  CPU was calibrated with ACPI PM Timer
0:100  0:000  BootloaderChooserX64 : Image base = 0x8D322000
0:100  0:000  Now is 16.08.2022,  10:14:18 (GMT)
0:100  0:000  Starting unknown on American Megatrends EFI
0:259  0:159  SelfDirPath = \EFI\BOOT
0:260  0:000  \EFI\BOOT\BLC.plist loaded: Success
0:260  0:000  === [ InitScreen ] ==============================
0:305  0:045  Console modes reported: 4, available modes:
0:306  0:001   - [01]: 80x25
0:307  0:001   - [03]: 100x31
0:309  0:001   - [04]: 170x40 (current mode)
0:310  0:001    Selected mode (4) is already set
0:311  0:001  === [ ScanVolumes ] =============================
0:313  0:001  === [ ScanLoaders ] =============================
0:453  0:140  UI ready
2:912  2:459  === [ StartLoader ] =============================
2:915  0:002  Start image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi
2:945  0:030  Boot image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi, status=Success
2:947  0:001  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
0:100  0:100  MemLog inited, TSC freq: 2194921485
0:100  0:000  CPU was calibrated with ACPI PM Timer
0:100  0:000  BootloaderChooserX64 : Image base = 0x8D322000
0:100  0:000  Now is 16.08.2022,  10:15:49 (GMT)
0:100  0:000  Starting unknown on American Megatrends EFI
0:470  0:370  SelfDirPath = \EFI\BOOT
0:471  0:000  \EFI\BOOT\BLC.plist loaded: Success
0:471  0:000  === [ InitScreen ] ==============================
0:518  0:047  Console modes reported: 4, available modes:
0:519  0:001   - [01]: 80x25
0:521  0:001   - [03]: 100x31
0:522  0:001   - [04]: 170x40 (current mode)
0:523  0:001    Selected mode (4) is already set
0:525  0:001  === [ ScanVolumes ] =============================
0:526  0:001  === [ ScanLoaders ] =============================
0:697  0:170  UI ready
2:223  1:526  === [ StartLoader ] =============================
2:226  0:002  Start image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi
2:255  0:029  Boot image PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(1,GPT,613F6FB5-7C19-4D0C-B41F-71EDF403F064,0x800,0x15E000)\EFI\CLOVER\CLOVERX64.efi, status=Success
2:256  0:001  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
`
But CHOOSE MENU always appear when machine startup

**Comment by jief666** [comment]
Because your timeout is 1. Set it to 0 to not see the menu.

**Comment by oldman20** [comment]
I set TimeOut=0 but just like this, still can't see bootchooser like it is

https://user-images.githubusercontent.com/39668756/185303984-f8c75c68-2205-4b37-884e-88db967ce258.mp4

**Comment by jief666** [comment]
Not sure what you mean. Did you press a key while booting ?

**Comment by oldman20** [comment]
Oh, i retry with HOLD KEY, not press key and it working!

**Comment by jief666** [comment]
Ok, good. Enjoy.
