### ISSUE TITLE
Option to exclude which efi files in scan list?

### ISSUE THREAD

**Issue by oldman20** [jief666/BootloaderChooser#5]
Can u make option for disable which efi files invisible in BootloaderChooser? I have too much efi files - which including efi files not use!
Many thank
![20221122_080313.jpg](https://user-images.githubusercontent.com/39668756/203189461-c76fadbc-5895-46d6-b788-2f6bf40c4e49.jpg)

**Comment by jief666** [comment]
Sorry I didn't see your issue before. I hate when people play dead...

I don't have time to do this. I'm not even convince that it's a good idea. BootloaderChooser is made to stay invisible most of the time. Timeout is supposed to be 0 second (or maybe 1 second). Your boot loader is suppose to give you the choice on what to boot. BootloaderChooser is made for when you have a problem launching your bootloader, typically after a bootloader upgrade. Which is suppose to happen very rarely (unless you are a bootloader developer or beta tester).

That said, if someone wants to submit a pull request, I'd take it.
