### ISSUE TITLE
No OpenCore GUI when using OC 0.8.9

### ISSUE THREAD

**Issue by 5T33Z0** [jief666/BootloaderChooser#6]
**Description**: after selecting OpenCore in BootloaderChoosr, the screen goes black (not turning off), and the default OS starts after the waiting time defined in the config.

My guess is that this is related to recent changes added in OpenCore 0.8.9:

>- Implemented firmware driver enabling pre-OpenCore graphics on non-natively supported GPUs on EFI-era Macs
>- Prevented unwanted clear screen to console background colour when in graphics mode

**Comment by jief666** [comment]
I don't think I will have time to try to fix this. And I don't have the hardware for it.
But I will very soon commit the source code (I know, I was suppose to do that years ago) so some else can...
Sorry.

**Comment by 5T33Z0** [comment]
Looking forward for the Source Code so someone elce can continue to work on it.

**Comment by 5T33Z0** [comment]
I found a solution:

- Enable `DirectGopRendering` so the OC Gui is displayed again after selecting OC from Bootloader Chooser's menu
- Optionally, enable `GopBurstMode` &rarr; slightly reduces loading time of the OC GUI (may vary from system to system)
