### ISSUE TITLE
Timeout value not respected in latest release v1.2 ?

### ISSUE THREAD

**Issue by mackonsti** [jief666/BootloaderChooser#7]
Hello @jief666 thank you for your latest release v1.20.

I think there is a small bug, however. When replacing the EFI binary file with your latest one, whilst keeping the same settings `BLC.plist` it seems that the value of `Timeout` is no longer taken into consideration?

```
<key>Timeout</key>
<integer>3</integer>
```

Upon reboot, I saw very very briefly the BootloaderChooser screen and it immediately switched to my normal OC Picker screen.

Does your new version still have a timeout feature for selecting different bootloaders? Has it changed parameter name?

Thanks for investigating...

P.S. For the sake of uniformity can you confirm if the PLIST key names are case-sensitive? I ask because in the past your **debug** key was with a lower-case style instead of capitalised like others 😄 perhaps consider fixing it too?

Here is my `BLC.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Timeout</key>
    <integer>3</integer>
    <key>DefaultVolume</key>
    <string>PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,12-37-B1-91-51-38-25-00)\HD(1,GPT,923D67C7-E015-4354-8579-496A4D7F523A,0x28,0x64000)\EFI\OC\OpenCore.efi</string>
    <key>debug</key>
    <string>false</string>
</dict>
```

Thanks.

**Comment by jief666** [comment]
Yes, I have to correct the timeout.
I will check for the debug key.
Thanks.

**Comment by jief666** [comment]
Done. Thanks for reporting.
Note that you can also start release version of OpenCore now.

**Comment by mackonsti** [comment]
Many thanks @jief666 ! Have a nice rest of summer.

**Comment by mackonsti** [comment]
Many thanks @jief666 ! Have a nice rest of summer.
P.S. What do you mean exactly by "start release version of OpenCore now"?
Sorry, I must have been missing something 😄 
Is this related to the "OC check removed" in your release comment?
